name: Build DCMTK for Windows with JPEG 2000 Support

on:
  workflow_dispatch:

jobs:
  build-dcmtk:
    runs-on: windows-latest

    steps:
    - name: Checkout DCMTK source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install ninja git -y

    - name: Clone and build OpenJPEG
      run: |
        git clone https://github.com/uclouvain/openjpeg.git C:\openjpeg
        cmake -S C:\openjpeg -B C:\openjpeg\build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
        cmake --build C:\openjpeg\build --config Release

    - name: Configure DCMTK with OpenJPEG support
      run: |
        mkdir C:\dcmtk_build
        cmake -S . -B C:\dcmtk_build `
          -G "Ninja" `
          -DCMAKE_BUILD_TYPE=Release `
          -DDCMTK_WITH_OPENJPEG=ON `
          -DOPENJPEG_INCLUDE_DIR="C:/openjpeg/src/lib/openjp2" `
          -DOPENJPEG_LIBRARY="C:/openjpeg/build/bin/Release/openjp2.lib"

    - name: Build DCMTK
      run: cmake --build C:\dcmtk_build --config Release

    - name: Upload Artifact (Windows Binaries)
      uses: actions/upload-artifact@v3
      with:
        name: dcmtk-windows-jpeg2000
        path: |
          C:\dcmtk_build\bin\Release\
